name: openfe-benchmarks
channels:
  - conda-forge
dependencies:
  - gufe
  - openfe
  # testing
  - nbval
  - pytest
  - pytest-xdist
  - pytest-cov
  - coverage
  - matplotlib
  - loguru
  # not sure why we don't install from conda-forge
  - pip
  - pip:
      - py3dmol
